include:
  - project: "GNOME/citemplates"
    file: "templates/default-rules.yml"
  - component: gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master
    inputs:
      job-name: "build-gnomeos"
      run-tests: "no"
  - component: gitlab.gnome.org/GNOME/citemplates/gnomeos-basic-ci@master
    inputs:
      job-name: "build-gnomeos-with-x11"
      meson-options: "-Dx11=true"
      run-tests: "no"
  - component: "gitlab.gnome.org/GNOME/citemplates/basic-deploy-docs@adrianvovk/basic-docs-subdir"
    inputs:
      docs-artifact-subdir: "./gnome-session/html/"
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    inputs:
      dist-job-name: "build-gnomeos"

build-fedora:
  stage: "build"
  image: "fedora:42"
  variables:
    _DEST: "$CI_PROJECT_DIR/destdir/"
    MESON_OPTIONS: >-
      --prefix=/usr
      -Ddocbook=false
      -Dman=false
    DEPENDENCIES: >-
      gcc
      git
      json-glib-devel
      meson
      systemd
      systemd-devel
      gtk4-devel
      gnome-desktop4-devel
  before_script:
    - dnf install -y --setopt=install_weak_deps=false $DEPENDENCIES
  script:
    - meson setup _build $MESON_OPTIONS $EXTRA_OPTIONS
    - meson compile -C _build
    - meson test -C _build --print-errorlogs --no-stdsplit --no-rebuild
    - meson dist -C _build --no-tests
    - mkdir -p $_DEST
    - meson install -C _build --no-rebuild --destdir="$_DEST"
  after_script:
    # Cleanup the destdir and thus container volume once we are done
    - rm -rvf $_DEST
  parallel:
    matrix:
      - EXTRA_OPTIONS: "-Dx11=true"
      - EXTRA_OPTIONS: ""
  artifacts:
    expire_in: "2 days"
    when: "always"
    paths:
      - "_build/meson-logs/"
    reports:
      junit: "_build/meson-logs/testlog.junit.xml"

xmllint:
  image: "quay.io/gnome_infrastructure/gnome-build-meta:core-nightly"
  stage: "build"
  needs: []
  script:
    - find . -name "*.xml" -exec xmllint --noout {} +
