workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

variables:
  COMMON_BUILD_OPTIONS: "--prefix=/usr -Ddocbook=false -Dman=false"
  COMMON_DEPENDENCIES: >-
    gcc
    git
    json-glib-devel
    meson
    systemd
    systemd-devel
    gtk3-devel
    gnome-desktop3-devel
  DEPS_X11: >-
    $COMMON_DEPENDENCIES
    libX11-devel
    libSM-devel
    libICE-devel
    xorg-x11-xtrans-devel
    libglvnd-devel
    libepoxy-devel
    libXcomposite-devel

build-fedora:
  image: fedora:40
  stage: build
  before_script:
    - dnf install -y --setopt=install_weak_deps=false $DEPENDENCIES
  script:
    - meson setup _build $MESON_OPTIONS
    - meson compile -C _build
    - meson test -C _build --print-errorlogs --no-stdsplit --no-rebuild
    - meson dist -C _build --no-tests

    - export _DEST="$CI_PROJECT_DIR/destdir/"
    - mkdir -p "$CI_PROJECT_DIR/destdir/"
    - meson install -C _build --no-rebuild --destdir="$_DEST"
  parallel:
    matrix:
      - MESON_OPTIONS: "$COMMON_BUILD_OPTIONS"
        DEPENDENCIES: "$DEPS_X11"
      - MESON_OPTIONS: "$COMMON_BUILD_OPTIONS -Dx11=false"
        DEPENDENCIES: "$COMMON_DEPENDENCIES"
