default:
  interruptible: true
  # Auto-retry jobs in case of infra failures
  retry:
    max: 1
    when:
      - 'runner_system_failure'
      - 'stuck_or_timeout_failure'
      - 'scheduler_failure'
      - 'api_failure'

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

variables:
  COMMON_BUILD_OPTIONS: "--prefix=/usr"

.build:
  stage: "build"
  variables:
    _DEST: "$CI_PROJECT_DIR/destdir/"
  script:
    - meson setup _build $MESON_OPTIONS
    - meson compile -C _build
    - meson test -C _build --print-errorlogs --no-stdsplit --no-rebuild
    - meson dist -C _build --no-tests

    - mkdir -p $_DEST
    - meson install -C _build --no-rebuild --destdir="$_DEST"
  after_script:
    # Cleanup the destdir and thus container volume once we are done
    - rm -rvf $_DEST
  artifacts:
    expire_in: "2 days"
    when: "always"
    paths:
      - "_build/meson-logs/"
    reports:
      junit: "_build/meson-logs/testlog.junit.xml"

build-fedora:
  extends: ".build"
  image: "fedora:40"
  variables:
    FEDORA_MESON_OPTIONS: "$COMMON_BUILD_OPTIONS -Ddocbook=false -Dman=false"
    COMMON_DEPENDENCIES: >-
      gcc
      git
      json-glib-devel
      meson
      systemd
      systemd-devel
      gtk3-devel
      gnome-desktop3-devel
    DEPS_X11: >-
      $COMMON_DEPENDENCIES
      libX11-devel
      libSM-devel
      libICE-devel
      xorg-x11-xtrans-devel
      libglvnd-devel
      libepoxy-devel
      libXcomposite-devel
  before_script:
    - dnf install -y --setopt=install_weak_deps=false $DEPENDENCIES
  parallel:
    matrix:
      - MESON_OPTIONS: "$FEDORA_MESON_OPTIONS"
        DEPENDENCIES: "$DEPS_X11"
      - MESON_OPTIONS: "$FEDORA_MESON_OPTIONS -Dx11=false"
        DEPENDENCIES: "$COMMON_DEPENDENCIES"

build-gnomeos:
  extends: ".build"
  image: "quay.io/gnome_infrastructure/gnome-build-meta:core-nightly"
  parallel:
    matrix:
      - MESON_OPTIONS: "$COMMON_BUILD_OPTIONS"
      - MESON_OPTIONS: "$COMMON_BUILD_OPTIONS -Dx11=false"
